#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\Temp\Prak1\PPC_ML310_Tutorial_10_1\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/Programme/Xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = C:/Programme/Xilinx/10.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-6

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp Lab1_Task3/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error yes

TESTAPP_MEMORY_OUTPUT_DIR = TestApp_Memory
TESTAPP_MEMORY_OUTPUT = $(TESTAPP_MEMORY_OUTPUT_DIR)/executable.elf

BLINKER_OUTPUT_DIR = Blinker
BLINKER_OUTPUT = $(BLINKER_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

BRAMINIT_ELF_FILES =  $(BLINKER_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0 $(BLINKER_OUTPUT) 

ALL_USER_ELF_FILES = $(TESTAPP_MEMORY_OUTPUT) $(BLINKER_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X C:/Temp/Prak1/PPC_ML310_Tutorial_10_1/ -E C:/Temp/Prak1/PPC_ML310_Tutorial_10_1/


LIBRARIES =  \
       ppc405_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = ppc405_0_libsclean 

PROGRAMCLEAN_TARGETS = TestApp_Memory_programclean Blinker_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/jtagppc_cntlr_0_wrapper.ngc \
implementation/plb0_wrapper.ngc \
implementation/xps_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/rs232_uart_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc \
implementation/xps_timer_1_wrapper.ngc \
implementation/xps_bram_if_cntlr_2_wrapper.ngc \
implementation/xps_bram_if_cntlr_2_bram_wrapper.ngc \
implementation/ppc405_0_iocm_wrapper.ngc \
implementation/ppc405_0_iocm_cntlr_wrapper.ngc \
implementation/isocm_bram_wrapper.ngc \
implementation/ppc405_0_docm_wrapper.ngc \
implementation/ppc405_0_docm_cntlr_wrapper.ngc \
implementation/dsocm_bram_wrapper.ngc \
implementation/orgate_1_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/xps_intc_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION TESTAPP_MEMORY
#################################################################

TESTAPP_MEMORY_SOURCES = /cygdrive/c/Temp/Prak1/PPC_ML310_Tutorial_10_1/TestApp_Memory/src/TestApp_Memory.c 

TESTAPP_MEMORY_HEADERS = 

TESTAPP_MEMORY_CC = powerpc-eabi-gcc
TESTAPP_MEMORY_CC_SIZE = powerpc-eabi-size
TESTAPP_MEMORY_CC_OPT = -O2
TESTAPP_MEMORY_CFLAGS = 
TESTAPP_MEMORY_CC_SEARCH = # -B
TESTAPP_MEMORY_LIBPATH = -L./ppc405_0/lib/ # -L
TESTAPP_MEMORY_INCLUDES = -I./ppc405_0/include/ # -I
TESTAPP_MEMORY_LFLAGS = # -l
TESTAPP_MEMORY_LINKER_SCRIPT = /cygdrive/c/Temp/Prak1/PPC_ML310_Tutorial_10_1/TestApp_Memory/src/TestApp_Memory_LinkScr.ld
TESTAPP_MEMORY_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_MEMORY_LINKER_SCRIPT) 
TESTAPP_MEMORY_CC_DEBUG_FLAG =  -g 
TESTAPP_MEMORY_CC_PROFILE_FLAG = # -pg
TESTAPP_MEMORY_CC_GLOBPTR_FLAG= # -msdata=eabi
TESTAPP_MEMORY_CC_INFERRED_FLAGS= 
TESTAPP_MEMORY_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
TESTAPP_MEMORY_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_MEMORY_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_MEMORY_OTHER_CC_FLAGS= $(TESTAPP_MEMORY_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_MEMORY_CC_START_ADDR_FLAG) $(TESTAPP_MEMORY_CC_STACK_SIZE_FLAG) $(TESTAPP_MEMORY_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_MEMORY_CC_INFERRED_FLAGS)  \
                  $(TESTAPP_MEMORY_LINKER_SCRIPT_FLAG) $(TESTAPP_MEMORY_CC_DEBUG_FLAG) $(TESTAPP_MEMORY_CC_PROFILE_FLAG) 

#################################################################
# SOFTWARE APPLICATION BLINKER
#################################################################

BLINKER_SOURCES = /cygdrive/c/Temp/Prak1/PPC_ML310_Tutorial_10_1/blinker/src/Blinker.c 

BLINKER_HEADERS = 

BLINKER_CC = powerpc-eabi-gcc
BLINKER_CC_SIZE = powerpc-eabi-size
BLINKER_CC_OPT = -O2
BLINKER_CFLAGS = 
BLINKER_CC_SEARCH = # -B
BLINKER_LIBPATH = -L./ppc405_0/lib/ # -L
BLINKER_INCLUDES = -I./ppc405_0/include/ # -I
BLINKER_LFLAGS = # -l
BLINKER_LINKER_SCRIPT = /cygdrive/c/Temp/Prak1/PPC_ML310_Tutorial_10_1/TestApp_Memory/src/TestApp_Memory_LinkScr.ld
BLINKER_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(BLINKER_LINKER_SCRIPT) 
BLINKER_CC_DEBUG_FLAG =  -g 
BLINKER_CC_PROFILE_FLAG = # -pg
BLINKER_CC_GLOBPTR_FLAG= # -msdata=eabi
BLINKER_CC_INFERRED_FLAGS= 
BLINKER_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
BLINKER_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
BLINKER_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
BLINKER_OTHER_CC_FLAGS= $(BLINKER_CC_GLOBPTR_FLAG)  \
                  $(BLINKER_CC_START_ADDR_FLAG) $(BLINKER_CC_STACK_SIZE_FLAG) $(BLINKER_CC_HEAP_SIZE_FLAG)  \
                  $(BLINKER_CC_INFERRED_FLAGS)  \
                  $(BLINKER_LINKER_SCRIPT_FLAG) $(BLINKER_CC_DEBUG_FLAG) $(BLINKER_CC_PROFILE_FLAG) 
